@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>> {
    ' ===== Interfaces =====
    Class "<<interface>>\nReadOnlyMaplet" as ReadOnlyMaplet
    Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
    Class "<<interface>>\nModel" as Model
    ' ===== Core Classes =====
    Class Maplet
    Class ModelManager
    Class UserPrefs

    ' ===== Data Structures =====
    Class UniqueAttractionList
    Class Attraction
    Class Name
    Class Contact
    Class Priority
    Class Address
    Class Activity


    ' ===== New Feature Classes =====
    Class Itinerary
    Class UniqueItineraryList
    Class ItineraryName

    Class Location
    Class UniqueLocationList
    Class LocationName

    Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

' ===== Inheritance =====
Maplet .up.|> ReadOnlyMaplet
ModelManager .up.|> Model
UserPrefs .up.|> ReadOnlyUserPrefs


' ===== Model dependencies =====
Model .left.> ReadOnlyMaplet
Model .right.> ReadOnlyUserPrefs
ModelManager -left-> "1" Maplet
ModelManager -right-> "1" UserPrefs
ModelManager --> "~* filtered" Attraction


' ===== Maplet composition =====
Maplet *--> "1" UniqueAttractionList
UniqueAttractionList --> "~* all" Attraction

' ===== Attraction composition =====
Attraction *--> Name
Attraction *--> Contact
Attraction *--> Priority
Attraction *--> Address
Attraction *--> "*" Activity

' ===== New feature compositions =====
Maplet *--> "1" UniqueItineraryList
UniqueItineraryList --> "*" Itinerary
Itinerary *--> ItineraryName
Itinerary *--> "*" Attraction

Maplet *--> "1" UniqueLocationList
UniqueLocationList --> "*" Location
Location *--> LocationName
Location *--> "*" Attraction

' ===== Layout alignment =====
Attraction -[hidden]up--> I
UniqueAttractionList -[hidden]right-> I
Name -[hidden]right-> Contact
Contact -[hidden]right-> Priority
Priority -[hidden]right-> Address
@enduml
