@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedMaplet" as VersionedMaplet MODEL_COLOR
end box

[-> Model : undoMaplet()
activate Model

Model -> VersionedMaplet : undo()
activate VersionedMaplet

VersionedMaplet -> VersionedMaplet :resetData(ReadOnlyMaplet)
VersionedMaplet --> Model :
deactivate VersionedMaplet

[<-- Model
deactivate Model

@enduml
